from tkinter import*
root=Tk()
root.title("memorizer")
open=Button(root,text="Open",width=10)
open.pack(side=LEFT,padx=5,pady=5)
delete=Button(root,text="Delete",width=10)
delete.pack(side=RIGHT,padx=5,pady=5)
save=Button(root,text="Save",width=10)
save.pack(padx=5,pady=5)
add=Button(root,text="Add",width=10)
add.pack(padx=5,pady=5)
item=Entry(root,width=20)
item.pack(padx=5,pady=5)
frame=Frame(root)
scrollbar=Scrollbar(frame,orient="vertical")
scrollbar.pack(side=RIGHT,fill=Y)
listbox=Listbox(frame,width=30,yscrollcommand=scrollbar.set,bg="cyan")
for i in range(1,10):
    listbox.insert(END,"eniola"+str(i))
    
listbox.pack(side=LEFT,padx=5,pady=5)
scrollbar.config(command=listbox.yview)
frame.pack(side=RIGHT)
root.mainloop()